apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "release.fullname" . }}-backend-configmap
  labels:
  {{- include "release.labels" . | nindent 4 }}
data:
  SEMANTIC_LOGGER_APP: spacedust-backend
  DATABASE_NAME: {{ .Values.config.databaseName | quote }}
  DATABASE_USER: {{ .Values.config.databaseUser | quote }}
  DATABASE_HOST: {{ .Values.config.databaseHost | default (printf "%s-db" (include "release.fullname" .)) | quote }}
  RELEASE_CLOUD_PROVIDER: {{ required "config.cloudProvider is required" .Values.config.cloudProvider | quote }}
  RELEASE_CLOUD_ROLE: {{ required "config.cloudRole is required" .Values.config.cloudRole | quote }}
  RELEASE_CLUSTER_CONTEXT: {{ required "config.clusterContext is required" .Values.config.clusterContext | quote }}
  RELEASE_CLUSTER_REGION: {{ required "config.clusterRegion is required" .Values.config.clusterRegion | quote }}
  RELEASE_ACCOUNT_NAME: {{ required "config.accountName is required" .Values.config.accountName | quote }}
  RELEASE_VCS_PLATFORM: {{ required "config.vcsPlatform is required" .Values.config.vcsPlatform | quote }}
  RELEASE_VCS_URL: {{ required "config.vcsUrl is required" .Values.config.vcsUrl | quote }}
  RELEASE_GITLAB_APP_CLIENT_ID: {{ required "config.gitlabAppClientId is required" .Values.config.gitlabAppClientId | quote }}
  RELEASE_SUPERUSER_EMAIL: {{ required "config.superuserEmail is required" .Values.config.superuserEmail | quote }}
  ADMIN_UI_USERNAME: {{ required "config.superuserEmail is required" .Values.config.superuserEmail | quote }}
  RELEASE_SUBDOMAIN: {{ required "config.clusterSubdomain is required" .Values.config.clusterSubdomain | quote }}
  SYMMETRIC_ENCRYPTION_CONFIG: /config/symmetric-encryption.yml
  RAILS_CREDENTIALS_CONTENT_PATH: /config/credentials.yml.enc
  TEMPORAL_HOST: {{ include "temporal.componentname" (list . "frontend") }}
  TEMPORAL_PORT: "7233"
  TEMPORAL_NAMESPACE: release
  TEMPORAL_CLI_ADDRESS: {{ include "temporal.fullname" . }}-frontend:{{ include "temporal.frontend.grpcPort" . }}
  AWS_MAX_IAM_SESSION_SECONDS: "3600"
  RAILS_FORCE_SSL: 'true'
  RAILS_LOG_TO_STDOUT: 'true'
  RAILS_SERVE_STATIC_FILES: 'true'
  
  # For temporal admintools
  SQL_PLUGIN: postgres
  SQL_PORT: "5432"
  SQL_USER: {{ .Values.config.databaseUser | default "" | quote }}
  SQL_HOST: {{ .Values.config.databaseHost | default (printf "%s-db" (include "release.fullname" .)) | quote }}
