apiVersion: v1
kind: Secret
metadata:
  name: {{ include "release.fullname" . }}-backend-secret
  labels:
  {{- include "release.labels" . | nindent 4 }}
data:
  CLOUD_RESOURCE_CLI_KEY: {{ .Values.config.cloudResourceCliKey | default "" | b64enc | quote }}
  RELEASE_SUPERUSER_PASSWORD: {{ required "config.superuserPassword is required" .Values.config.superuserPassword | b64enc | quote }}
  DATABASE_PASSWORD: {{ .Values.config.databasePassword | default "" | b64enc | quote }}
  DATABASE_USER: {{ .Values.config.databaseUser | default "" | b64enc | quote }}
  DATABASE_HOST: {{ .Values.config.databaseHost | default "" | b64enc | quote }}

  # For temporal admintools
  SQL_PASSWORD: {{ .Values.config.databasePassword | default "" | b64enc | quote }}
  SQL_USER: {{ .Values.config.databaseUser | default "" | b64enc | quote }}
  SQL_HOST: {{ .Values.config.databaseHost | default "" | b64enc | quote }}
