apiVersion: v1
kind: Secret
metadata:
  name: {{ include "release.fullname" . }}-backend-secret
  labels:
  {{- include "release.labels" . | nindent 4 }}
data:
  CLOUD_RESOURCE_CLI_KEY: {{ .Values.config.cloudResourceCliKey | default "" | b64enc | quote }}
  RELEASE_SUPERUSER_PASSWORD: {{ required "config.superuserPassword is required" .Values.config.superuserPassword | b64enc | quote }}
