apiVersion: v1
kind: Secret
metadata:
  name: {{ include "release.fullname" . }}-backend-secret
  labels:
  {{- include "release.labels" . | nindent 4 }}
data:
  CLOUD_RESOURCE_CLI_KEY: {{ .Values.config.cloudResourceCliKey | default "" | b64enc | quote }}
  RELEASE_SUPERUSER_PASSWORD: {{ required "config.superuserPassword is required" .Values.config.superuserPassword | b64enc | quote }}
  ADMIN_UI_PASSWORD: {{ required "config.superuserPassword is required" .Values.config.superuserPassword | b64enc | quote }}
  RELEASE_GITLAB_APP_CLIENT_SECRET: {{ required "config.gitlabAppClientSecret is required" .Values.config.gitlabAppClientSecret | b64enc | quote }}
  DATABASE_PASSWORD: {{ .Values.config.databasePassword | default "" | b64enc | quote }}

  # For temporal admintools
  SQL_PASSWORD: {{ .Values.config.databasePassword | default "" | b64enc | quote }}
  SQL_USER: {{ .Values.config.databaseUser | default "" | b64enc | quote }}
  SQL_HOST: {{ .Values.config.databaseHost | default (printf "%s-db" (include "release.fullname" .)) | quote }}

  RAILS_MASTER_KEY: {{ include "railsMasterKeySecretEncoded" . }}
