apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "release.fullname" . }}-backend-configmap
  labels:
  {{- include "release.labels" . | nindent 4 }}
data:
  SEMANTIC_LOGGER_APP: spacedust-backend
  RELEASE_ACCOUNT_NAME: {{ required "config.accountName is required" .Values.config.accountName | quote }}
  RELEASE_VCS_URL: {{ required "config.vcsUrl is required" .Values.config.vcsUrl | quote }}
  RELEASE_SUPERUSER_EMAIL: {{ required "config.superuserEmail is required" .Values.config.superuserEmail | quote }}
  SYMMETRIC_ENCRYPTION_CONFIG: /config/symmetric-encryption.yml
  TEMPORAL_HOST: {{ include "temporal.componentname" (list . "frontend") }}
  TEMPORAL_PORT: "7233"
  TEMPORAL_NAMESPACE: release
  
  # For temporal admintools
  SQL_PLUGIN: postgres
  SQL_PORT: "5432"
