apiVersion: v1
kind: Secret
metadata:
  name: {{ include "release.fullname" . }}-common-secret
  labels:
  {{- include "release.labels" . | nindent 4 }}
data:
  WORKOS_API_KEY: {{ .Values.config.workosApiKey | default "" | b64enc | quote }}
  WORKOS_WEBHOOK_SECRET: {{ .Values.config.workosWebhookSecret | default "" | b64enc | quote }}
  BITBUCKET_APP_CLIENT_SECRET: {{ .Values.config.bitbucketAppClientSecret | default "" | b64enc | quote }}
  GITLAB_APP_CLIENT_SECRET: {{ .Values.config.gitlabAppClientSecret | default "" | b64enc | quote }}
  ANALYTICS_GOOGLE_SERVICE_ACCOUNT_CREDS_PATH: {{ .Values.config.analyticsGoogleServiceAccountCredsPath | default "" | b64enc | quote }}
  ANALYTICS_REDSHIFT_DB_URL: {{ .Values.config.analyticsRedshiftDbUrl | default "" | b64enc | quote }}
  CHARGEBEE_API_KEY: {{ .Values.config.chargebeeApiKey | default "" | b64enc | quote }}
  CHARGEBEE_WEBHOOK_USERNAME: {{ .Values.config.chargebeeWebhookUsername | default "" | b64enc | quote }}
  CHARGEBEE_WEBHOOK_PASSWORD: {{ .Values.config.chargebeeWebhookPassword | default "" | b64enc | quote }}
  GITLAB_CLIENT_SECRET: {{ .Values.config.gitlabClientSecret | default "" | b64enc | quote }}
  MAILCHIMP_ENDPOINT: {{ .Values.config.mailchimpEndpoint | default "" | b64enc | quote }}
  STRIPE_PUBLISHABLE_API_KEY: {{ .Values.config.stripePublishableApiKey | default "" | b64enc | quote }}
  STRIPE_SECRET_API_KEY: {{ .Values.config.stripeSecretApiKey | default "" | b64enc | quote }}
  STRIPE_WEBHOOK_SIGNING_SECRET: {{ .Values.config.stripeWebhookSigningSecret | default "" | b64enc | quote }}
  GITHUB_APP_CLIENT_ID: {{ .Values.config.githubAppClientId | default "" | b64enc | quote }}
  GITHUB_APP_PEM_KEY: {{ .Values.config.githubAppPemKey | default "" | b64enc | quote }}
  GITHUB_APP_CLIENT_SECRET: {{ .Values.config.githubAppClientSecret | default "" | b64enc | quote }}
  GITHUB_APP_WEBHOOK_SECRET: {{ .Values.config.githubAppWebhookSecret | default "" | b64enc | quote }}
  AIRTABLE_API_KEY: {{ .Values.config.airtableApiKey | default "" | b64enc | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.config.awsAccessKeyId | default "" | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.config.awsSecretAccessKey | default "" | b64enc | quote }}
  BITBUCKET_CLIENT_ID: {{ .Values.config.bitbucketClientId | default "" | b64enc | quote }}
  BITBUCKET_CLIENT_SECRET: {{ .Values.config.bitbucketClientSecret | default "" | b64enc | quote }}
  GITHUB_CLIENT_ID: {{ .Values.config.githubClientId | default "" | b64enc | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.config.githubClientSecret | default "" | b64enc | quote }}
  RAILS_MASTER_KEY: {{ .Values.config.railsMasterKey | default "" | b64enc | quote }}
  RELEASEUSER_AUTH_TOKEN: {{ .Values.config.releaseuserAuthToken | default "" | b64enc | quote }}
  RELEASEUSER_IDENTITY_AUTH_TOKEN: {{ .Values.config.releaseuserIdentityAuthToken | default "" | b64enc | quote }}
  RELEASEUSER_PASSWORD: {{ .Values.config.releaseuserPassword | default "" | b64enc | quote }}
  RELEASEUSER_PRIVATE_KEY: {{ .Values.config.releaseuserPrivateKey | default "" | b64enc | quote }}
  RELEASEUSER_PUBLIC_KEY: {{ .Values.config.releaseuserPublicKey | default "" | b64enc | quote }}
  SENDGRID_API_KEY: {{ .Values.config.sendgridApiKey | default "" | b64enc | quote }}
  SLACK_APP_ID: {{ .Values.config.slackAppId | default "" | b64enc | quote }}
  SLACK_BOT_TOKEN: {{ .Values.config.slackBotToken | default "" | b64enc | quote }}
  SLACK_CLIENT_ID: {{ .Values.config.slackClientId | default "" | b64enc | quote }}
  SLACK_CLIENT_SECRET: {{ .Values.config.slackClientSecret | default "" | b64enc | quote }}
  RELEASE_AUTHENTICATION_TOKEN: {{ .Values.config.releaseAuthenticationToken | default "" | b64enc | quote }}
  NEXT_PUBLIC_ENVIRONMENT_TYPE: {{ .Values.config.nextPublicEnvironmentType | default "" | b64enc | quote }}
  CONTENTFUL_SPACE_ID: {{ .Values.config.contentfulSpaceId | default "" | b64enc | quote }}
  CONTENTFUL_ACCESS_TOKEN: {{ .Values.config.contentfulAccessToken | default "" | b64enc | quote }}
  STATIC_BUILD_AWS_ACCESS_ID: {{ .Values.config.staticBuildAwsAccessId | default "" | b64enc | quote }}
  STATIC_BUILD_AWS_SECRET_KEY: {{ .Values.config.staticBuildAwsSecretKey | default "" | b64enc | quote }}
  STATIC_BUILD_AWS_KEY: {{ .Values.config.staticBuildAwsKey | default "" | b64enc | quote }}
  NODE_ENV: {{ .Values.config.nodeEnv | default "" | b64enc | quote }}
  BUILDPLATFORM: {{ .Values.config.buildplatform | default "" | b64enc | quote }}
  TARGETARCH: {{ .Values.config.targetarch | default "" | b64enc | quote }}
  TARGETPLATFORM: {{ .Values.config.targetplatform | default "" | b64enc | quote }}
  CONTENTFUL_PREVIEW_TOKEN: {{ .Values.config.contentfulPreviewToken | default "" | b64enc | quote }}
  RELEASE_STATIC_BUILD_DEPLOY_KEY: {{ .Values.config.releaseStaticBuildDeployKey | default "" | b64enc | quote }}
  RELEASE_STATIC_BUILD_AWS_ACCESS_KEY_ID: {{ .Values.config.releaseStaticBuildAwsAccessKeyId | default "" | b64enc | quote }}
  RELEASE_STATIC_BUILD_AWS_SECRET_ACCESS_KEY: {{ .Values.config.releaseStaticBuildAwsSecretAccessKey | default "" | b64enc | quote }}
  RELEASE_STATIC_BUILD_AWS_SESSION_TOKEN: {{ .Values.config.releaseStaticBuildAwsSessionToken | default "" | b64enc | quote }}
  FRESHPAINT_CLIENT_ID: {{ .Values.config.freshpaintClientId | default "" | b64enc | quote }}
  REACT_APP_FRESHPAINT_ID: {{ .Values.config.reactAppFreshpaintId | default "" | b64enc | quote }}
