apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "release.fullname" . }}-config
  labels:
  {{- include "release.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 5Gi
