apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "release.fullname" . }}-config
  labels:
  {{- include "release.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.config.storageClassName | default (print (include "release.fullname" . ) "-nfs") }}
  resources:
    requests:
      storage: 5Gi
