apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "release.fullname" . }}-console
  labels:
  {{- include "release.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.console.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: console
      tier: console
      {{- include "release.labels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: console
        tier: console
        {{- include "release.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include "checksumTemplates" (list $ "common-configmap" "common-secret" "backend-configmap" "backend-secret" "console-secret") }}
    spec:
      containers:
      - command:
        - bash
        - -c
        - cd /app/console/server && yarn start
        image: {{ .Values.containerRegistry.host}}/release/spacedust/backend:{{ .Values.tag }}
        imagePullPolicy: Always
        name: console
        envFrom:
        - configMapRef:
            name: {{ include "release.fullname" . }}-common-configmap
        - secretRef:
            name: {{ include "release.fullname" . }}-common-secret
        - configMapRef:
            name: {{ include "release.fullname" . }}-backend-configmap
        - secretRef:
            name: {{ include "release.fullname" . }}-backend-secret
        - secretRef:
            name: {{ include "release.fullname" . }}-console-secret
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 3000
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - curl
            - -Lf
            - http://localhost:3000/health
          failureThreshold: 30
          periodSeconds: 5
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 100Mi
      - name: backend
        image: {{ .Values.containerRegistry.host}}/release/spacedust/backend:{{ .Values.tag }}
        imagePullPolicy: Always
        command:
        - bash
        - -c
        - RAILS_FORCE_SSL=false bundle exec rails s -p 3000 -b 0.0.0.0 
        envFrom:
        - configMapRef:
            name: {{ include "release.fullname" . }}-common-configmap
        - secretRef:
            name: {{ include "release.fullname" . }}-common-secret
        - configMapRef:
            name: {{ include "release.fullname" . }}-backend-configmap
        - secretRef:
            name: {{ include "release.fullname" . }}-backend-secret
        - secretRef:
            name: {{ include "release.fullname" . }}-console-secret
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: {{ include "release.fullname" . }}-config
      imagePullSecrets:
      - name: {{ include "release.fullname" . }}-registry-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "release.fullname" . }}-console
  labels:
    app: console
    {{- include "release.labels" . | nindent 4 }}
spec:
  type: {{ .Values.console.type }}
  selector:
    app: console
    tier: console
    {{- include "release.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.console.ports | toYaml | nindent 2 -}}
