apiVersion: v1
kind: Secret
metadata:
  name: {{ include "release.fullname" . }}-console-configmap
  labels:
  {{- include "release.labels" . | nindent 4 }}
data:
  CLOUD_RESOURCE_CLI_KEY: {{ .Values.config.cloudResourceCliKey | default "" | b64enc | quote }}
