{{- if $.Values.storageClass.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
  {{- include "release.labels" . | nindent 4 }}
  name: {{ include "release.fullname" . }}-nfs
parameters:
  uid: "50377"
  gid: "50377"
  directoryPerms: "700"
  fileSystemId: {{ required "config.efsFilesystemId is required" .Values.config.efsFilesystemId }}
  provisioningMode: efs-ap
provisioner: efs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
{{- end }}
