apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "release.fullname" . }}-redis
  labels:
  {{- include "release.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      tier: redis
  template:
    metadata:
      labels:
        app: redis
        tier: redis
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - name: redis
          containerPort: 6379
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "release.fullname" . }}-redis
  labels:
    app: redis
  {{- include "release.labels" . | nindent 4 }}
  annotations:
spec:
  selector:
    app: redis
    tier: redis
  ports:
    - name: redis
      port: 6379
