apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "release.fullname" . }}-redis
  labels:
  {{- include "release.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      tier: redis
      {{- include "release.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: redis
        tier: redis
        {{- include "release.labels" . | nindent 8 }}
    spec:
      containers:
      - name: redis
        image: bitnami/redis
        ports:
        - name: redis
          containerPort: 6379
          protocol: TCP
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "release.fullname" . }}-redis
  labels:
    app: redis
    {{- include "release.labels" . | nindent 4 }}
  annotations:
spec:
  selector:
    app: redis
    tier: redis
    {{- include "release.selectorLabels" . | nindent 4 }}
  ports:
    - name: redis
      port: 6379
