apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ include "release.fullname" . }}-registry-secrets
  labels:
  {{- include "release.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
