apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "release.fullname" . }}-cluster-admin
  namespace: {{ .Release.Namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.config.serviceAccountCloudRole | quote }}
