apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "release.fullname" . }}-cluster-admin
  namespace: {{ .Release.Namespace }}
{{- with .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
