apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "release.fullname" . }}-sidekiq
  labels:
  {{- include "release.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.sidekiq.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: sidekiq
      tier: sidekiq
      {{- include "release.labels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sidekiq
        tier: sidekiq
        {{- include "release.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include "checksumTemplates" (list $ "common-configmap" "common-secret" "backend-configmap" "backend-secret" "sidekiq-configmap") }}
    spec:
      serviceAccountName: {{ template "release.fullname" . }}-cluster-admin
      containers:
      - command:
        - bundle
        - exec
        - sidekiq
        envFrom:
        - configMapRef:
            name: {{ include "release.fullname" . }}-common-configmap
        - secretRef:
            name: {{ include "release.fullname" . }}-common-secret
        - configMapRef:
            name: {{ include "release.fullname" . }}-backend-configmap
        - secretRef:
            name: {{ include "release.fullname" . }}-backend-secret
        - configMapRef:
            name: {{ include "release.fullname" . }}-sidekiq-configmap
        image: {{ .Values.containerRegistry.host}}/release/spacedust/backend:{{ .Values.tag }}
        imagePullPolicy: Always
        name: sidekiq
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 1Gi
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: {{ include "release.fullname" . }}-config
      imagePullSecrets:
      - name: {{ include "release.fullname" . }}-registry-secrets
