apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "temporal.componentname" (list $ "admintools") }}"
  labels:
    {{- include "release.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: admintools
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "temporal.name" . }}
        helm.sh/chart: {{ include "temporal.chart" . }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
        app.kubernetes.io/component: admintools
        app.kubernetes.io/part-of: {{ .Chart.Name }}
        {{- with $.Values.temporal.admintools.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with $.Values.temporal.admintools.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{ include "temporal.serviceAccount" . }}
      containers:
        - name: admin-tools
          image: "{{ .Values.temporal.admintools.image.repository }}:{{ .Values.temporal.admintools.image.tag }}"
          imagePullPolicy: {{ .Values.temporal.admintools.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 22
              protocol: TCP
          envFrom:
          - configMapRef:
              name: {{ include "release.fullname" . }}-common-configmap
          - secretRef:
              name: {{ include "release.fullname" . }}-common-secret
          - configMapRef:
              name: {{ include "release.fullname" . }}-backend-configmap
          - secretRef:
              name: {{ include "release.fullname" . }}-backend-secret
          livenessProbe:
              exec:
                command:
                - ls
                - /
              initialDelaySeconds: 5
              periodSeconds: 5
