{{- if $.Values.temporal.server.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "temporal.fullname" . }}-dynamic-config"
  labels:
    app.kubernetes.io/name: {{ include "temporal.name" . }}
    helm.sh/chart: {{ include "temporal.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
data:
  dynamic_config.yaml: |-
  {{- if $.Values.temporal.server.dynamicConfig }}
    {{- toYaml .Values.temporal.server.dynamicConfig | nindent 4 }}
  {{- end }}
{{- end }}
