apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "release.fullname" . }}-temporal-workers
  labels:
  {{- include "release.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.temporal.workers.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: temporal-workers
      tier: temporal-workers
      {{- include "release.labels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: temporal-workers
        tier: temporal-workers
        {{- include "release.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include "checksumTemplates" (list $ "common-configmap" "common-secret" "backend-configmap" "backend-secret" "temporal-workers-configmap") }}
    spec:
      serviceAccountName: {{ template "release.fullname" . }}-cluster-admin
      containers:
      - name: temporal-worker
        command:
        - bundle
        - exec
        - ./bin/temporal-worker
        envFrom:
        - configMapRef:
            name: {{ include "release.fullname" . }}-common-configmap
        - secretRef:
            name: {{ include "release.fullname" . }}-common-secret
        - configMapRef:
            name: {{ include "release.fullname" . }}-backend-configmap
        - secretRef:
            name: {{ include "release.fullname" . }}-backend-secret
        - configMapRef:
            name: {{ include "release.fullname" . }}-temporal-workers-configmap
        image: {{ .Values.containerRegistry.host}}/release/spacedust/backend:{{ .Values.tag }}
        imagePullPolicy: Always
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: {{ include "release.fullname" . }}-config
      imagePullSecrets:
      - name: {{ include "release.fullname" . }}-registry-secrets
